// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC43e9Cii2DaQZSXLfyx26Qsh7UHD8Tupo',
    appId: '1:321399962691:web:9f3477434c7673dda768f6',
    messagingSenderId: '321399962691',
    projectId: 'sparvoll2-4c20a',
    authDomain: 'sparvoll2-4c20a.firebaseapp.com',
    storageBucket: 'sparvoll2-4c20a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzZi6btBOE9IN_Y0NAgop29B-cE5ORSkE',
    appId: '1:321399962691:android:a41c747561955d2ba768f6',
    messagingSenderId: '321399962691',
    projectId: 'sparvoll2-4c20a',
    storageBucket: 'sparvoll2-4c20a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLuZmfcGrj90qeQweG-KYXqMZzlw_2WKo',
    appId: '1:321399962691:ios:841228b47d74ce15a768f6',
    messagingSenderId: '321399962691',
    projectId: 'sparvoll2-4c20a',
    storageBucket: 'sparvoll2-4c20a.appspot.com',
    androidClientId: '321399962691-hgvn69p7dnq3fe9risrmt1aou0ppbqhh.apps.googleusercontent.com',
    iosClientId: '321399962691-b9i391soi97f9ku8oo6qff8eu11hduot.apps.googleusercontent.com',
    iosBundleId: 'com.example.sparvollTheApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC43e9Cii2DaQZSXLfyx26Qsh7UHD8Tupo',
    appId: '1:321399962691:web:cbbe6d282e0c549ca768f6',
    messagingSenderId: '321399962691',
    projectId: 'sparvoll2-4c20a',
    authDomain: 'sparvoll2-4c20a.firebaseapp.com',
    storageBucket: 'sparvoll2-4c20a.appspot.com',
  );

}