import '../../../routes/routes.dart';
import '../../personalisation/models/address_model.dart';
import '../../personalisation/models/user_model.dart';
import '../../utils/constants/enums.dart';
import '../../utils/constants/image_strings.dart';
import '../models/banner_model.dart';
import '../models/brand_category_model.dart';
import '../models/brand_model.dart';
import '../models/cart_item_model.dart';
import '../models/cart_model.dart';
import '../models/category_model.dart';
import '../models/order_model.dart';
import '../models/product_attribute_model.dart';
import '../models/product_category_model.dart';
import '../models/product_model.dart';
import '../models/product_review_model.dart';
import '../models/product_variation_model.dart';

class TDummyData {
  /// -- Banners
  static final List<BannerModel> banners = [
    BannerModel(imageUrl: TImages.banner1, targetScreen: TRoutes.order, active: false),
    BannerModel(imageUrl: TImages.banner2, targetScreen: TRoutes.cart, active: true),
    BannerModel(imageUrl: TImages.banner3, targetScreen: TRoutes.favourites, active: true),
    BannerModel(imageUrl: TImages.banner4, targetScreen: TRoutes.search, active: true),
    BannerModel(imageUrl: TImages.banner5, targetScreen: TRoutes.settings, active: true),
    BannerModel(imageUrl: TImages.banner6, targetScreen: TRoutes.userAddress, active: true),
    BannerModel(imageUrl: TImages.banner8, targetScreen: TRoutes.checkout, active: false),
  ];

  /// -- User
  static final UserModel user = UserModel(
    firstName: 'Coding',
    lastName: 'with T',
    email: 'support@codingwithT.com',
    phoneNumber: '+14155552671',
    profilePicture: TImages.user,
    addresses: [
      AddressModel(
        id: '1',
        name: 'Coding with T',
        phoneNumber: '+923178059528',
        street: '82356 Timmy Coves',
        city: 'South Liana',
        state: 'Maine',
        postalCode: '87665',
        country: 'USA',
      ),
      AddressModel(
        id: '6',
        name: 'John Doe',
        phoneNumber: '+1234567890',
        street: '123 Main Street',
        city: 'New York',
        state: 'New York',
        postalCode: '10001',
        country: 'United States',
      ),
      AddressModel(
        id: '2',
        name: 'Alice Smith',
        phoneNumber: '+9876543210',
        street: '456 Elm Avenue',
        city: 'Los Angeles',
        state: 'California',
        postalCode: '90001',
        country: 'United States',
      ),
      AddressModel(
        id: '3',
        name: 'Taimoor Sikander',
        phoneNumber: '+923178059528',
        street: 'Street 35',
        city: 'Islamabad',
        state: 'Federal',
        postalCode: '48000',
        country: 'Pakistan',
      ),
      AddressModel(
        id: '4',
        name: 'Maria Garcia',
        phoneNumber: '+5412345678',
        street: '789 Oak Road',
        city: 'Buenos Aires',
        state: 'Buenos Aires',
        postalCode: '1001',
        country: 'Argentina',
      ),
      AddressModel(
        id: '5',
        name: 'Liam Johnson',
        phoneNumber: '+447890123456',
        street: '10 Park Lane',
        city: 'London',
        state: 'England',
        postalCode: 'SW1A 1AA',
        country: 'United Kingdom',
      )
    ],
    username: '',
    id: '',
  );

  /// -- Cart
  static final CartModel cart = CartModel(
    cartId: '001',
    items: [
      CartItemModel(
        productId: '001',
        variationId: '1',
        quantity: 1,
        title: products[0].title,
        image: products[0].thumbnail,
        brandName: products[0].brand!.name,
        price: products[0].productVariations![0].price,
        selectedVariation: products[0].productVariations![0].attributeValues,
      ),
      CartItemModel(
        productId: '002',
        variationId: '',
        quantity: 1,
        title: products[1].title,
        image: products[1].thumbnail,
        brandName: products[1].brand!.name,
        price: products[1].price,
        selectedVariation: products[1].productVariations != null ? products[1].productVariations![1].attributeValues : {},
      ),
    ],
  );

  /// -- Order
  static final List<OrderModel> orders = [
    OrderModel(
        id: 'CWT0012',
        status: OrderStatus.processing,
        items: cart.items,
        totalAmount: 265,
        orderDate: DateTime(2023, 09, 1),
        deliveryDate: DateTime(2023, 09, 9)),
    OrderModel(
        id: 'CWT0025',
        status: OrderStatus.shipped,
        items: cart.items,
        totalAmount: 369,
        orderDate: DateTime(2023, 10, 2),
        deliveryDate: DateTime(2023, 10, 6)),
    OrderModel(
        id: 'CWT0152',
        status: OrderStatus.delivered,
        items: cart.items,
        totalAmount: 254,
        orderDate: DateTime(2023, 11, 3),
        deliveryDate: DateTime(2023, 11, 8)),
    OrderModel(
        id: 'CWT0265',
        status: OrderStatus.delivered,
        items: cart.items,
        totalAmount: 355,
        orderDate: DateTime(2023, 12, 20),
        deliveryDate: DateTime(2023, 12, 25)),
    OrderModel(
        id: 'CWT1536',
        status: OrderStatus.delivered,
        items: cart.items,
        totalAmount: 115,
        orderDate: DateTime(2023, 12, 25),
        deliveryDate: DateTime(2024, 01, 1)),
  ];

  /// -- List of all Categories
  static final List<CategoryModel> categories = [
    CategoryModel(id: '1', image: TImages.mobileIcon, name: 'Mobile', isFeatured: true),
    CategoryModel(id: '2', image: TImages.tabletIcon, name: 'Tablets', isFeatured: true),
    CategoryModel(id: '5', image: TImages.wearablesIcon, name: 'Wearables', isFeatured: true),
    CategoryModel(id: '3', image: TImages.gamingIcon, name: 'Gaming', isFeatured: true),
    CategoryModel(id: '4', image: TImages.multimediaIcon, name: 'Multimedia', isFeatured: true),
    CategoryModel(id: '6', image: TImages.accessoriesIcon, name: 'Accessories', isFeatured: true),
    CategoryModel(id: '7', image: TImages.outletIcon, name: 'outlet', isFeatured: true),
    CategoryModel(id: '24', image: TImages.enterpriseIcon, name: 'Enterprise', isFeatured: true),

    ///subcategories
    CategoryModel(id: '8', image: TImages.appleLogo, name: 'Apple Smartphone', parentId: '1', isFeatured: false),
    CategoryModel(id: '9', image: TImages.samsungLogo, name: 'Samsung Smartphone', parentId: '1', isFeatured: false),
    CategoryModel(id: '10', image: TImages.xiaomiLogo, name: 'Xiaomi Smartphones', parentId: '1', isFeatured: false),
    CategoryModel(id: '11', image: TImages.googleLogo, name: 'Google Smartphones', parentId: '1', isFeatured: false),
    CategoryModel(id: '12', image: TImages.nokiaLogo, name: 'Nokia Smartphones', parentId: '1', isFeatured: false),
    CategoryModel(id: '13', image: TImages.sonyLogo, name: 'Sony Smartphones', parentId: '1', isFeatured: false),
    CategoryModel(id: '14', image: TImages.motorolaLogo, name: 'Motorola Smartphones', parentId: '1', isFeatured: false),
    //tablets
    CategoryModel(id: '15', image: TImages.appleLogo, name: 'Apple Tablets', parentId: '2', isFeatured: false),
    CategoryModel(id: '16', image: TImages.samsungLogo, name: 'Samsung Tablets', parentId: '2', isFeatured: false),
    CategoryModel(id: '17', image: TImages.xiaomiLogo, name: 'Xiaomi Tablets', parentId: '2', isFeatured: false),
    CategoryModel(id: '18', image: TImages.microsoftLogo, name: 'Microsoft Tablets', parentId: '2', isFeatured: false),
    CategoryModel(id: '19', image: TImages.lenovoLogo, name: 'Lenovo Tablets', parentId: '2', isFeatured: false),

    //gaming
    CategoryModel(id: '20', image: TImages.electronicsIcon, name: 'Laptop', parentId: '2', isFeatured: false),
    CategoryModel(id: '21', image: TImages.electronicsIcon, name: 'Mobile', parentId: '2', isFeatured: false),
  ];

  /// -- List of all Brands
  static final List<BrandModel> brands = [
    BrandModel(id: '1', image: TImages.samsungLogo, name: 'Samsung', productsCount: 265, isFeatured: true),
    BrandModel(id: '2', image: TImages.googleLogo, name: 'Google', productsCount: 95, isFeatured: true),
    BrandModel(id: '8', image: TImages.nokiaLogo, name: 'Nokia', productsCount: 36, isFeatured: false),
    BrandModel(id: '5', image: TImages.microsoftLogo, name: 'Microsoft', productsCount: 36, isFeatured: false),
    BrandModel(id: '3', image: TImages.appleLogo, name: 'Apple', productsCount: 16, isFeatured: true),
    BrandModel(id: '4', image: TImages.xiaomiLogo, name: 'Xiaomi', productsCount: 36, isFeatured: false),
    BrandModel(id: '6', image: TImages.lenovoLogo, name: 'Lenovo', productsCount: 36, isFeatured: true),
    BrandModel(id: '7', image: TImages.motorolaLogo, name: 'Motorola', productsCount: 65, isFeatured: false),
    BrandModel(id: '9', image: TImages.electronicsIcon, name: 'other brands', productsCount: 36, isFeatured: false),
    BrandModel(id: '10', image: TImages.sonyIcon, name: 'Sony', productsCount: 36, isFeatured: false),

  ];

  /// -- List of all Brand Categories
  static final List<BrandCategoryModel> brandCategory = [
    BrandCategoryModel(brandId: '1', categoryId: '1'),
    BrandCategoryModel(brandId: '1', categoryId: '2'),
    BrandCategoryModel(brandId: '1', categoryId: '4'),
    BrandCategoryModel(brandId: '1', categoryId: '5'),
    BrandCategoryModel(brandId: '1', categoryId: '6'),
    BrandCategoryModel(brandId: '1', categoryId: '7'),
    BrandCategoryModel(brandId: '1', categoryId: '9'),
    BrandCategoryModel(brandId: '1', categoryId: '16'),
    BrandCategoryModel(brandId: '1', categoryId: '22'),
    BrandCategoryModel(brandId: '1', categoryId: '24'),
    BrandCategoryModel(brandId: '1', categoryId: '25'),
    BrandCategoryModel(brandId: '1', categoryId: '26'),
    BrandCategoryModel(brandId: '1', categoryId: '27'),
    BrandCategoryModel(brandId: '1', categoryId: '28'),
    BrandCategoryModel(brandId: '1', categoryId: '29'),

    BrandCategoryModel(brandId: '3', categoryId: '1'),
    BrandCategoryModel(brandId: '3', categoryId: '2'),
    BrandCategoryModel(brandId: '3', categoryId: '4'),
    BrandCategoryModel(brandId: '3', categoryId: '5'),
    BrandCategoryModel(brandId: '3', categoryId: '6'),
    BrandCategoryModel(brandId: '3', categoryId: '7'),
    BrandCategoryModel(brandId: '3', categoryId: '8'),
    BrandCategoryModel(brandId: '3', categoryId: '15'),
    BrandCategoryModel(brandId: '3', categoryId: '21'),
    BrandCategoryModel(brandId: '3', categoryId: '25'),
    BrandCategoryModel(brandId: '3', categoryId: '26'),
    BrandCategoryModel(brandId: '3', categoryId: '27'),
    BrandCategoryModel(brandId: '3', categoryId: '28'),

    BrandCategoryModel(brandId: '2', categoryId: '1'),
    BrandCategoryModel(brandId: '1', categoryId: '6'),
    BrandCategoryModel(brandId: '2', categoryId: '7'),
    BrandCategoryModel(brandId: '2', categoryId: '11'),
    BrandCategoryModel(brandId: '2', categoryId: '24'),
    BrandCategoryModel(brandId: '2', categoryId: '25'),

    BrandCategoryModel(brandId: '4', categoryId: '1'),
    BrandCategoryModel(brandId: '4', categoryId: '6'),
    BrandCategoryModel(brandId: '4', categoryId: '7'),
    BrandCategoryModel(brandId: '4', categoryId: '10'),
    BrandCategoryModel(brandId: '4', categoryId: '17'),
    BrandCategoryModel(brandId: '4', categoryId: '24'),
    BrandCategoryModel(brandId: '4', categoryId: '25'),

    BrandCategoryModel(brandId: '5', categoryId: '1'),
    BrandCategoryModel(brandId: '5', categoryId: '2'),
    BrandCategoryModel(brandId: '5', categoryId: '3'),
    BrandCategoryModel(brandId: '5', categoryId: '6'),
    BrandCategoryModel(brandId: '5', categoryId: '7'),
    BrandCategoryModel(brandId: '5', categoryId: '18'),
    BrandCategoryModel(brandId: '5', categoryId: '25'),
    BrandCategoryModel(brandId: '5', categoryId: '26'),
    BrandCategoryModel(brandId: '5', categoryId: '29'),

    BrandCategoryModel(brandId: '6', categoryId: '2'),
    BrandCategoryModel(brandId: '6', categoryId: '19'),
    BrandCategoryModel(brandId: '6', categoryId: '26'),
    BrandCategoryModel(brandId: '6', categoryId: '6'),
    BrandCategoryModel(brandId: '6', categoryId: '19'),
    BrandCategoryModel(brandId: '6', categoryId: '26'),

    BrandCategoryModel(brandId: '7', categoryId: '1'),
    BrandCategoryModel(brandId: '7', categoryId: '6'),
    BrandCategoryModel(brandId: '7', categoryId: '7'),
    BrandCategoryModel(brandId: '7', categoryId: '14'),
    BrandCategoryModel(brandId: '7', categoryId: '24'),
    BrandCategoryModel(brandId: '7', categoryId: '25'),

    BrandCategoryModel(brandId: '8', categoryId: '12'),
    BrandCategoryModel(brandId: '8', categoryId: '1'),

    BrandCategoryModel(brandId: '9', categoryId: '6'),
    BrandCategoryModel(brandId: '9', categoryId: '7'),
    BrandCategoryModel(brandId: '9', categoryId: '29'),
    BrandCategoryModel(brandId: '9', categoryId: '3'),
    BrandCategoryModel(brandId: '9', categoryId: '4'),

    BrandCategoryModel(brandId: '10', categoryId: '1'),
    BrandCategoryModel(brandId: '10', categoryId: '13'),
    BrandCategoryModel(brandId: '10', categoryId: '3'),
    BrandCategoryModel(brandId: '10', categoryId: '24'),
    BrandCategoryModel(brandId: '10', categoryId: '25'),

  ];

  /// -- List of all Product Categories
  static final List<ProductCategoryModel> productCategories = [
    ProductCategoryModel(productId: '001', categoryId: '1'),
    ProductCategoryModel(productId: '001', categoryId: '8'),
    ProductCategoryModel(productId: '002', categoryId: '1'),
    ProductCategoryModel(productId: '002', categoryId: '8'),
    ProductCategoryModel(productId: '003', categoryId: '1'),
    ProductCategoryModel(productId: '003', categoryId: '8'),
    ProductCategoryModel(productId: '004', categoryId: '1'),
    ProductCategoryModel(productId: '004', categoryId: '8'),
    ProductCategoryModel(productId: '005', categoryId: '1'),
    ProductCategoryModel(productId: '005', categoryId: '8'),
    ProductCategoryModel(productId: '006', categoryId: '1'),
    ProductCategoryModel(productId: '006', categoryId: '8'),
    ProductCategoryModel(productId: '007', categoryId: '1'),
    ProductCategoryModel(productId: '007', categoryId: '8'),
    ProductCategoryModel(productId: '008', categoryId: '1'),
    ProductCategoryModel(productId: '008', categoryId: '8'),
    ProductCategoryModel(productId: '009', categoryId: '1'),
    ProductCategoryModel(productId: '009', categoryId: '8'),
    ProductCategoryModel(productId: '010', categoryId: '1'),
    ProductCategoryModel(productId: '010', categoryId: '8'),
    ProductCategoryModel(productId: '011', categoryId: '1'),
    ProductCategoryModel(productId: '011', categoryId: '8'),
    ProductCategoryModel(productId: '012', categoryId: '1'),
    ProductCategoryModel(productId: '012', categoryId: '8'),
    ProductCategoryModel(productId: '013', categoryId: '1'),
    ProductCategoryModel(productId: '013', categoryId: '8'),
    ProductCategoryModel(productId: '014', categoryId: '1'),
    ProductCategoryModel(productId: '014', categoryId: '8'),
    ProductCategoryModel(productId: '015', categoryId: '1'),
    ProductCategoryModel(productId: '015', categoryId: '8'),
    ProductCategoryModel(productId: '016', categoryId: '1'),
    ProductCategoryModel(productId: '016', categoryId: '8'),
    ProductCategoryModel(productId: '017', categoryId: '1'),
    ProductCategoryModel(productId: '017', categoryId: '9'),
    ProductCategoryModel(productId: '019', categoryId: '1'),
    ProductCategoryModel(productId: '019', categoryId: '8'),


    ProductCategoryModel(productId: '018', categoryId: '1'),
    ProductCategoryModel(productId: '018', categoryId: '9'),
    ProductCategoryModel(productId: '020', categoryId: '1'),
    ProductCategoryModel(productId: '020', categoryId: '9'),
    ProductCategoryModel(productId: '021', categoryId: '1'),
    ProductCategoryModel(productId: '021', categoryId: '9'),
    ProductCategoryModel(productId: '022', categoryId: '1'),
    ProductCategoryModel(productId: '022', categoryId: '9'),
    ProductCategoryModel(productId: '023', categoryId: '1'),
    ProductCategoryModel(productId: '023', categoryId: '9'),
    ProductCategoryModel(productId: '024', categoryId: '1'),
    ProductCategoryModel(productId: '024', categoryId: '9'),
    ProductCategoryModel(productId: '025', categoryId: '1'),
    ProductCategoryModel(productId: '025', categoryId: '9'),
    ProductCategoryModel(productId: '026', categoryId: '1'),
    ProductCategoryModel(productId: '026', categoryId: '9'),
    ProductCategoryModel(productId: '026', categoryId: '24'),
    ProductCategoryModel(productId: '027', categoryId: '1'),
    ProductCategoryModel(productId: '027', categoryId: '9'),
    ProductCategoryModel(productId: '028', categoryId: '1'),
    ProductCategoryModel(productId: '028', categoryId: '9'),
    ProductCategoryModel(productId: '029', categoryId: '1'),
    ProductCategoryModel(productId: '029', categoryId: '9'),
    ProductCategoryModel(productId: '030', categoryId: '1'),
    ProductCategoryModel(productId: '030', categoryId: '9'),
    ProductCategoryModel(productId: '031', categoryId: '1'),
    ProductCategoryModel(productId: '031', categoryId: '9'),
    ProductCategoryModel(productId: '032', categoryId: '1'),
    ProductCategoryModel(productId: '032', categoryId: '9'),
    ProductCategoryModel(productId: '034', categoryId: '1'),
    ProductCategoryModel(productId: '034', categoryId: '9'),
    ProductCategoryModel(productId: '035', categoryId: '1'),
    ProductCategoryModel(productId: '035', categoryId: '9'),
    ProductCategoryModel(productId: '036', categoryId: '1'),
    ProductCategoryModel(productId: '036', categoryId: '9'),
    ProductCategoryModel(productId: '037', categoryId: '1'),
    ProductCategoryModel(productId: '037', categoryId: '9'),
    ProductCategoryModel(productId: '038', categoryId: '1'),
    ProductCategoryModel(productId: '038', categoryId: '9'),
    ProductCategoryModel(productId: '039', categoryId: '1'),
    ProductCategoryModel(productId: '039', categoryId: '9'),
    ProductCategoryModel(productId: '041', categoryId: '1'),
    ProductCategoryModel(productId: '041', categoryId: '9'),
    ProductCategoryModel(productId: '042', categoryId: '1'),
    ProductCategoryModel(productId: '042', categoryId: '9'),
    ProductCategoryModel(productId: '033', categoryId: '1'),
    ProductCategoryModel(productId: '033', categoryId: '9'),
    ProductCategoryModel(productId: '033', categoryId: '24'),
    ProductCategoryModel(productId: '040', categoryId: '1'),
    ProductCategoryModel(productId: '040', categoryId: '9'),
    ProductCategoryModel(productId: '040', categoryId: '24'),
    ProductCategoryModel(productId: '045', categoryId: '1'),
    ProductCategoryModel(productId: '045', categoryId: '9'),
    ProductCategoryModel(productId: '046', categoryId: '1'),
    ProductCategoryModel(productId: '046', categoryId: '9'),
    ProductCategoryModel(productId: '047', categoryId: '1'),
    ProductCategoryModel(productId: '047', categoryId: '9'),
    ProductCategoryModel(productId: '048', categoryId: '1'),
    ProductCategoryModel(productId: '048', categoryId: '9'),
    ProductCategoryModel(productId: '050', categoryId: '1'),
    ProductCategoryModel(productId: '050', categoryId: '9'),
    ProductCategoryModel(productId: '051', categoryId: '1'),
    ProductCategoryModel(productId: '051', categoryId: '9'),
    ProductCategoryModel(productId: '052', categoryId: '1'),
    ProductCategoryModel(productId: '052', categoryId: '9'),
    ProductCategoryModel(productId: '054', categoryId: '1'),
    ProductCategoryModel(productId: '054', categoryId: '9'),
    ProductCategoryModel(productId: '055', categoryId: '1'),
    ProductCategoryModel(productId: '055', categoryId: '9'),
    ProductCategoryModel(productId: '056', categoryId: '1'),
    ProductCategoryModel(productId: '056', categoryId: '9'),
    ProductCategoryModel(productId: '056', categoryId: '24'),
    ProductCategoryModel(productId: '057', categoryId: '1'),
    ProductCategoryModel(productId: '057', categoryId: '9'),
    ProductCategoryModel(productId: '058', categoryId: '1'),
    ProductCategoryModel(productId: '058', categoryId: '9'),
    ProductCategoryModel(productId: '058', categoryId: '24'),
    ProductCategoryModel(productId: '059', categoryId: '1'),
    ProductCategoryModel(productId: '059', categoryId: '9'),


    ProductCategoryModel(productId: '060', categoryId: '12'),
    ProductCategoryModel(productId: '060', categoryId: '1'),

    ProductCategoryModel(productId: '061', categoryId: '1'),
    ProductCategoryModel(productId: '061', categoryId: '11'),
    ProductCategoryModel(productId: '062', categoryId: '1'),
    ProductCategoryModel(productId: '062', categoryId: '11'),
    ProductCategoryModel(productId: '063', categoryId: '1'),
    ProductCategoryModel(productId: '063', categoryId: '11'),
    ProductCategoryModel(productId: '064', categoryId: '1'),
    ProductCategoryModel(productId: '064', categoryId: '11'),
    ProductCategoryModel(productId: '065', categoryId: '1'),
    ProductCategoryModel(productId: '065', categoryId: '11'),
    ProductCategoryModel(productId: '066', categoryId: '1'),
    ProductCategoryModel(productId: '066', categoryId: '11'),
    ProductCategoryModel(productId: '067', categoryId: '1'),
    ProductCategoryModel(productId: '067', categoryId: '11'),


    ProductCategoryModel(productId: '068', categoryId: '1'),
    ProductCategoryModel(productId: '068', categoryId: '14'),
    ProductCategoryModel(productId: '069', categoryId: '1'),
    ProductCategoryModel(productId: '069', categoryId: '14'),
    ProductCategoryModel(productId: '070', categoryId: '1'),
    ProductCategoryModel(productId: '070', categoryId: '14'),
    ProductCategoryModel(productId: '071', categoryId: '1'),
    ProductCategoryModel(productId: '071', categoryId: '14'),
    ProductCategoryModel(productId: '072', categoryId: '1'),
    ProductCategoryModel(productId: '072', categoryId: '14'),
    ProductCategoryModel(productId: '073', categoryId: '1'),
    ProductCategoryModel(productId: '073', categoryId: '14'),
    ProductCategoryModel(productId: '074', categoryId: '1'),
    ProductCategoryModel(productId: '074', categoryId: '14'),
    ProductCategoryModel(productId: '075', categoryId: '1'),
    ProductCategoryModel(productId: '075', categoryId: '14'),
    ProductCategoryModel(productId: '076', categoryId: '1'),
    ProductCategoryModel(productId: '076', categoryId: '14'),
    ProductCategoryModel(productId: '077', categoryId: '1'),
    ProductCategoryModel(productId: '077', categoryId: '14'),
    ProductCategoryModel(productId: '078', categoryId: '1'),
    ProductCategoryModel(productId: '078', categoryId: '14'),
    ProductCategoryModel(productId: '079', categoryId: '1'),
    ProductCategoryModel(productId: '079', categoryId: '14'),
    ProductCategoryModel(productId: '080', categoryId: '1'),
    ProductCategoryModel(productId: '080', categoryId: '14'),
    ProductCategoryModel(productId: '081', categoryId: '8'),
    ProductCategoryModel(productId: '081', categoryId: '14'),
    ProductCategoryModel(productId: '082', categoryId: '1'),
    ProductCategoryModel(productId: '082', categoryId: '14'),
    ProductCategoryModel(productId: '083', categoryId: '1'),
    ProductCategoryModel(productId: '083', categoryId: '14'),
    ProductCategoryModel(productId: '084', categoryId: '1'),
    ProductCategoryModel(productId: '084', categoryId: '14'),
    ProductCategoryModel(productId: '085', categoryId: '1'),
    ProductCategoryModel(productId: '085', categoryId: '14'),
    ProductCategoryModel(productId: '086', categoryId: '1'),
    ProductCategoryModel(productId: '086', categoryId: '14'),
    ProductCategoryModel(productId: '087', categoryId: '1'),
    ProductCategoryModel(productId: '087', categoryId: '14'),
    ProductCategoryModel(productId: '088', categoryId: '1'),
    ProductCategoryModel(productId: '088', categoryId: '14'),
    ProductCategoryModel(productId: '089', categoryId: '1'),
    ProductCategoryModel(productId: '089', categoryId: '14'),
    ProductCategoryModel(productId: '090', categoryId: '1'),
    ProductCategoryModel(productId: '090', categoryId: '13'),

    ProductCategoryModel(productId: '091', categoryId: '1'),
    ProductCategoryModel(productId: '091', categoryId: '10'),
    ProductCategoryModel(productId: '092', categoryId: '1'),
    ProductCategoryModel(productId: '092', categoryId: '10'),
    ProductCategoryModel(productId: '093', categoryId: '1'),
    ProductCategoryModel(productId: '093', categoryId: '10'),
    ProductCategoryModel(productId: '094', categoryId: '1'),
    ProductCategoryModel(productId: '094', categoryId: '10'),
    ProductCategoryModel(productId: '095', categoryId: '1'),
    ProductCategoryModel(productId: '095', categoryId: '10'),
    ProductCategoryModel(productId: '096', categoryId: '1'),
    ProductCategoryModel(productId: '096', categoryId: '10'),
    ProductCategoryModel(productId: '097', categoryId: '1'),
    ProductCategoryModel(productId: '097', categoryId: '10'),
    ProductCategoryModel(productId: '098', categoryId: '1'),
    ProductCategoryModel(productId: '098', categoryId: '10'),
    ProductCategoryModel(productId: '099', categoryId: '1'),
    ProductCategoryModel(productId: '099', categoryId: '10'),
    ProductCategoryModel(productId: '100', categoryId: '1'),
    ProductCategoryModel(productId: '100', categoryId: '10'),
    ProductCategoryModel(productId: '103', categoryId: '1'),
    ProductCategoryModel(productId: '103', categoryId: '10'),
    ProductCategoryModel(productId: '104', categoryId: '1'),
    ProductCategoryModel(productId: '104', categoryId: '10'),
    ProductCategoryModel(productId: '105', categoryId: '1'),
    ProductCategoryModel(productId: '105', categoryId: '10'),
    ProductCategoryModel(productId: '106', categoryId: '1'),
    ProductCategoryModel(productId: '106', categoryId: '10'),

    ProductCategoryModel(productId: '107', categoryId: '2'),
    ProductCategoryModel(productId: '107', categoryId: '16'),
    ProductCategoryModel(productId: '108', categoryId: '2'),
    ProductCategoryModel(productId: '108', categoryId: '16'),
    ProductCategoryModel(productId: '108', categoryId: '24'),
    ProductCategoryModel(productId: '109', categoryId: '2'),
    ProductCategoryModel(productId: '109', categoryId: '16'),
    ProductCategoryModel(productId: '110', categoryId: '2'),
    ProductCategoryModel(productId: '110', categoryId: '16'),
    ProductCategoryModel(productId: '111', categoryId: '2'),
    ProductCategoryModel(productId: '111', categoryId: '16'),
    ProductCategoryModel(productId: '112', categoryId: '2'),
    ProductCategoryModel(productId: '112', categoryId: '16'),
    ProductCategoryModel(productId: '113', categoryId: '2'),
    ProductCategoryModel(productId: '113', categoryId: '16'),
    ProductCategoryModel(productId: '114', categoryId: '2'),
    ProductCategoryModel(productId: '114', categoryId: '16'),
    ProductCategoryModel(productId: '115', categoryId: '2'),
    ProductCategoryModel(productId: '115', categoryId: '16'),
    ProductCategoryModel(productId: '116', categoryId: '2'),
    ProductCategoryModel(productId: '116', categoryId: '16'),
    ProductCategoryModel(productId: '116', categoryId: '24'),
    ProductCategoryModel(productId: '117', categoryId: '2'),
    ProductCategoryModel(productId: '117', categoryId: '16'),
    ProductCategoryModel(productId: '117', categoryId: '24'),
    ProductCategoryModel(productId: '118', categoryId: '2'),
    ProductCategoryModel(productId: '118', categoryId: '16'),
    ProductCategoryModel(productId: '118', categoryId: '24'),
    ProductCategoryModel(productId: '119', categoryId: '2'),
    ProductCategoryModel(productId: '119', categoryId: '16'),
    ProductCategoryModel(productId: '120', categoryId: '2'),
    ProductCategoryModel(productId: '120', categoryId: '16'),
    ProductCategoryModel(productId: '121', categoryId: '2'),
    ProductCategoryModel(productId: '121', categoryId: '16'),
    ProductCategoryModel(productId: '122', categoryId: '2'),
    ProductCategoryModel(productId: '122', categoryId: '16'),
    ProductCategoryModel(productId: '123', categoryId: '2'),
    ProductCategoryModel(productId: '123', categoryId: '16'),
    ProductCategoryModel(productId: '124', categoryId: '2'),
    ProductCategoryModel(productId: '124', categoryId: '16'),
    ProductCategoryModel(productId: '124', categoryId: '24'),
    ProductCategoryModel(productId: '125', categoryId: '2'),
    ProductCategoryModel(productId: '125', categoryId: '16'),
    ProductCategoryModel(productId: '125', categoryId: '24'),
    ProductCategoryModel(productId: '126', categoryId: '2'),
    ProductCategoryModel(productId: '126', categoryId: '16'),
    ProductCategoryModel(productId: '127', categoryId: '2'),
    ProductCategoryModel(productId: '127', categoryId: '16'),
    ProductCategoryModel(productId: '128', categoryId: '2'),
    ProductCategoryModel(productId: '128', categoryId: '16'),
    ProductCategoryModel(productId: '128', categoryId: '24'),

    ProductCategoryModel(productId: '129', categoryId: '2'),
    ProductCategoryModel(productId: '129', categoryId: '15'),
    ProductCategoryModel(productId: '130', categoryId: '2'),
    ProductCategoryModel(productId: '130', categoryId: '15'),
    ProductCategoryModel(productId: '131', categoryId: '2'),
    ProductCategoryModel(productId: '031', categoryId: '15'),
    ProductCategoryModel(productId: '132', categoryId: '2'),
    ProductCategoryModel(productId: '132', categoryId: '15'),
    ProductCategoryModel(productId: '133', categoryId: '2'),
    ProductCategoryModel(productId: '133', categoryId: '15'),
    ProductCategoryModel(productId: '134', categoryId: '2'),
    ProductCategoryModel(productId: '134', categoryId: '15'),
    ProductCategoryModel(productId: '135', categoryId: '2'),
    ProductCategoryModel(productId: '135', categoryId: '15'),
    ProductCategoryModel(productId: '136', categoryId: '2'),
    ProductCategoryModel(productId: '136', categoryId: '15'),
    ProductCategoryModel(productId: '137', categoryId: '2'),
    ProductCategoryModel(productId: '137', categoryId: '15'),

    ProductCategoryModel(productId: '138', categoryId: '2'),
    ProductCategoryModel(productId: '138', categoryId: '18'),
    ProductCategoryModel(productId: '139', categoryId: '2'),
    ProductCategoryModel(productId: '139', categoryId: '18'),
    ProductCategoryModel(productId: '140', categoryId: '2'),
    ProductCategoryModel(productId: '140', categoryId: '18'),
    ProductCategoryModel(productId: '141', categoryId: '2'),
    ProductCategoryModel(productId: '141', categoryId: '18'),

    ProductCategoryModel(productId: '142', categoryId: '2'),
    ProductCategoryModel(productId: '142', categoryId: '19'),
    ProductCategoryModel(productId: '143', categoryId: '2'),
    ProductCategoryModel(productId: '143', categoryId: '19'),
    ProductCategoryModel(productId: '144', categoryId: '52'),
    ProductCategoryModel(productId: '144', categoryId: '19'),
    ProductCategoryModel(productId: '145', categoryId: '2'),
    ProductCategoryModel(productId: '145', categoryId: '19'),

    ProductCategoryModel(productId: '146', categoryId: '5'),
    ProductCategoryModel(productId: '146', categoryId: '21'),
    ProductCategoryModel(productId: '147', categoryId: '5'),
    ProductCategoryModel(productId: '147', categoryId: '21'),
    ProductCategoryModel(productId: '148', categoryId: '5'),
    ProductCategoryModel(productId: '148', categoryId: '21'),
    ProductCategoryModel(productId: '149', categoryId: '5'),
    ProductCategoryModel(productId: '149', categoryId: '21'),
    ProductCategoryModel(productId: '150', categoryId: '5'),
    ProductCategoryModel(productId: '150', categoryId: '21'),
    ProductCategoryModel(productId: '151', categoryId: '5'),
    ProductCategoryModel(productId: '151', categoryId: '21'),
    ProductCategoryModel(productId: '152', categoryId: '5'),
    ProductCategoryModel(productId: '152', categoryId: '21'),
    ProductCategoryModel(productId: '153', categoryId: '5'),
    ProductCategoryModel(productId: '153', categoryId: '21'),

    ProductCategoryModel(productId: '154', categoryId: '5'),
    ProductCategoryModel(productId: '154', categoryId: '22'),
    ProductCategoryModel(productId: '155', categoryId: '5'),
    ProductCategoryModel(productId: '155', categoryId: '22'),
    ProductCategoryModel(productId: '156', categoryId: '5'),
    ProductCategoryModel(productId: '156', categoryId: '22'),
    ProductCategoryModel(productId: '157', categoryId: '5'),
    ProductCategoryModel(productId: '157', categoryId: '22'),
    ProductCategoryModel(productId: '158', categoryId: '5'),
    ProductCategoryModel(productId: '158', categoryId: '22'),
    ProductCategoryModel(productId: '159', categoryId: '5'),
    ProductCategoryModel(productId: '159', categoryId: '22'),
    ProductCategoryModel(productId: '160', categoryId: '5'),
    ProductCategoryModel(productId: '160', categoryId: '22'),
    ProductCategoryModel(productId: '161', categoryId: '5'),
    ProductCategoryModel(productId: '161', categoryId: '22'),

    ProductCategoryModel(productId: '162', categoryId: '3'),
    ProductCategoryModel(productId: '163', categoryId: '3'),
    ProductCategoryModel(productId: '164', categoryId: '3'),
    ProductCategoryModel(productId: '165', categoryId: '3'),
    ProductCategoryModel(productId: '166', categoryId: '3'),
    ProductCategoryModel(productId: '167', categoryId: '3'),
    ProductCategoryModel(productId: '168', categoryId: '3'),

    ProductCategoryModel(productId: '169', categoryId: '3'),
    ProductCategoryModel(productId: '170', categoryId: '3'),
    ProductCategoryModel(productId: '171', categoryId: '3'),
    ProductCategoryModel(productId: '172', categoryId: '3'),
    ProductCategoryModel(productId: '173', categoryId: '3'),
    ProductCategoryModel(productId: '174', categoryId: '3'),
    ProductCategoryModel(productId: '175', categoryId: '3'),
    ProductCategoryModel(productId: '176', categoryId: '3'),
    ProductCategoryModel(productId: '177', categoryId: '3'),
    ProductCategoryModel(productId: '179', categoryId: '3'),
    ProductCategoryModel(productId: '180', categoryId: '3'),

    ProductCategoryModel(productId: '181', categoryId: '24'),
    ProductCategoryModel(productId: '182', categoryId: '24'),
    ProductCategoryModel(productId: '183', categoryId: '24'),

    ProductCategoryModel(productId: '184', categoryId: '6'),
    ProductCategoryModel(productId: '184', categoryId: '28'),
    ProductCategoryModel(productId: '185', categoryId: '6'),
    ProductCategoryModel(productId: '185', categoryId: '28'),
    ProductCategoryModel(productId: '186', categoryId: '6'),
    ProductCategoryModel(productId: '186', categoryId: '28'),
    ProductCategoryModel(productId: '187', categoryId: '6'),
    ProductCategoryModel(productId: '187', categoryId: '28'),
    ProductCategoryModel(productId: '190', categoryId: '6'),
    ProductCategoryModel(productId: '190', categoryId: '28'),
    ProductCategoryModel(productId: '191', categoryId: '6'),
    ProductCategoryModel(productId: '191', categoryId: '28'),
    ProductCategoryModel(productId: '192', categoryId: '6'),
    ProductCategoryModel(productId: '192', categoryId: '28'),
    ProductCategoryModel(productId: '193', categoryId: '6'),
    ProductCategoryModel(productId: '193', categoryId: '28'),
    ProductCategoryModel(productId: '194', categoryId: '6'),
    ProductCategoryModel(productId: '194', categoryId: '28'),
    ProductCategoryModel(productId: '195', categoryId: '8'),
    ProductCategoryModel(productId: '195', categoryId: '28'),
    ProductCategoryModel(productId: '196', categoryId: '6'),
    ProductCategoryModel(productId: '196', categoryId: '28'),
    ProductCategoryModel(productId: '197', categoryId: '6'),
    ProductCategoryModel(productId: '197', categoryId: '28'),
    ProductCategoryModel(productId: '198', categoryId: '6'),
    ProductCategoryModel(productId: '198', categoryId: '28'),
    ProductCategoryModel(productId: '199', categoryId: '6'),
    ProductCategoryModel(productId: '199', categoryId: '28'),
    ProductCategoryModel(productId: '200', categoryId: '6'),
    ProductCategoryModel(productId: '200', categoryId: '28'),

    ProductCategoryModel(productId: '201', categoryId: '6'),
    ProductCategoryModel(productId: '201', categoryId: '29'),
    ProductCategoryModel(productId: '202', categoryId: '6'),
    ProductCategoryModel(productId: '202', categoryId: '29'),
    ProductCategoryModel(productId: '203', categoryId: '6'),
    ProductCategoryModel(productId: '203', categoryId: '29'),
    ProductCategoryModel(productId: '204', categoryId: '6'),
    ProductCategoryModel(productId: '204', categoryId: '29'),
    ProductCategoryModel(productId: '205', categoryId: '6'),
    ProductCategoryModel(productId: '205', categoryId: '29'),
    ProductCategoryModel(productId: '206', categoryId: '6'),
    ProductCategoryModel(productId: '206', categoryId: '29'),
    ProductCategoryModel(productId: '207', categoryId: '6'),
    ProductCategoryModel(productId: '207', categoryId: '29'),
    ProductCategoryModel(productId: '208', categoryId: '6'),
    ProductCategoryModel(productId: '208', categoryId: '29'),
    ProductCategoryModel(productId: '209', categoryId: '6'),
    ProductCategoryModel(productId: '209', categoryId: '29'),
    ProductCategoryModel(productId: '210', categoryId: '6'),
    ProductCategoryModel(productId: '210', categoryId: '29'),

    ProductCategoryModel(productId: '211', categoryId: '7'),
    ProductCategoryModel(productId: '211', categoryId: '25'),
    ProductCategoryModel(productId: '212', categoryId: '7'),
    ProductCategoryModel(productId: '212', categoryId: '25'),
    ProductCategoryModel(productId: '213', categoryId: '7'),
    ProductCategoryModel(productId: '213', categoryId: '25'),
    ProductCategoryModel(productId: '214', categoryId: '7'),
    ProductCategoryModel(productId: '214', categoryId: '25'),
    ProductCategoryModel(productId: '215', categoryId: '7'),
    ProductCategoryModel(productId: '215', categoryId: '25'),
    ProductCategoryModel(productId: '216', categoryId: '7'),
    ProductCategoryModel(productId: '216', categoryId: '25'),
    ProductCategoryModel(productId: '217', categoryId: '7'),
    ProductCategoryModel(productId: '217', categoryId: '25'),
    ProductCategoryModel(productId: '218', categoryId: '7'),
    ProductCategoryModel(productId: '218', categoryId: '25'),
    ProductCategoryModel(productId: '219', categoryId: '7'),
    ProductCategoryModel(productId: '219', categoryId: '25'),
    ProductCategoryModel(productId: '220', categoryId: '7'),
    ProductCategoryModel(productId: '220', categoryId: '25'),
    ProductCategoryModel(productId: '221', categoryId: '7'),
    ProductCategoryModel(productId: '221', categoryId: '25'),
    ProductCategoryModel(productId: '222', categoryId: '7'),
    ProductCategoryModel(productId: '222', categoryId: '25'),
    ProductCategoryModel(productId: '223', categoryId: '7'),
    ProductCategoryModel(productId: '223', categoryId: '25'),
    ProductCategoryModel(productId: '224', categoryId: '7'),
    ProductCategoryModel(productId: '224', categoryId: '25'),
    ProductCategoryModel(productId: '225', categoryId: '7'),
    ProductCategoryModel(productId: '225', categoryId: '25'),
    ProductCategoryModel(productId: '226', categoryId: '7'),
    ProductCategoryModel(productId: '226', categoryId: '25'),
    ProductCategoryModel(productId: '227', categoryId: '7'),
    ProductCategoryModel(productId: '227', categoryId: '25'),
    ProductCategoryModel(productId: '228', categoryId: '7'),
    ProductCategoryModel(productId: '228', categoryId: '25'),
    ProductCategoryModel(productId: '229', categoryId: '7'),
    ProductCategoryModel(productId: '229', categoryId: '25'),
    ProductCategoryModel(productId: '230', categoryId: '7'),
    ProductCategoryModel(productId: '230', categoryId: '25'),
    ProductCategoryModel(productId: '231', categoryId: '7'),
    ProductCategoryModel(productId: '231', categoryId: '25'),
    ProductCategoryModel(productId: '232', categoryId: '7'),
    ProductCategoryModel(productId: '232', categoryId: '25'),
    ProductCategoryModel(productId: '233', categoryId: '7'),
    ProductCategoryModel(productId: '233', categoryId: '25'),
    ProductCategoryModel(productId: '234', categoryId: '7'),
    ProductCategoryModel(productId: '234', categoryId: '25'),
    ProductCategoryModel(productId: '235', categoryId: '7'),
    ProductCategoryModel(productId: '235', categoryId: '25'),
    ProductCategoryModel(productId: '236', categoryId: '7'),
    ProductCategoryModel(productId: '236', categoryId: '25'),
    ProductCategoryModel(productId: '237', categoryId: '7'),
    ProductCategoryModel(productId: '237', categoryId: '25'),
    ProductCategoryModel(productId: '238', categoryId: '7'),
    ProductCategoryModel(productId: '238', categoryId: '25'),
    ProductCategoryModel(productId: '239', categoryId: '7'),
    ProductCategoryModel(productId: '239', categoryId: '25'),
    ProductCategoryModel(productId: '240', categoryId: '7'),
    ProductCategoryModel(productId: '240', categoryId: '25'),
    ProductCategoryModel(productId: '241', categoryId: '7'),
    ProductCategoryModel(productId: '241', categoryId: '25'),
    ProductCategoryModel(productId: '242', categoryId: '7'),
    ProductCategoryModel(productId: '242', categoryId: '25'),
    ProductCategoryModel(productId: '243', categoryId: '7'),
    ProductCategoryModel(productId: '243', categoryId: '25'),
    ProductCategoryModel(productId: '244', categoryId: '7'),
    ProductCategoryModel(productId: '244', categoryId: '25'),
    ProductCategoryModel(productId: '245', categoryId: '7'),
    ProductCategoryModel(productId: '245', categoryId: '25'),
    ProductCategoryModel(productId: '246', categoryId: '7'),
    ProductCategoryModel(productId: '246', categoryId: '25'),
    ProductCategoryModel(productId: '247', categoryId: '7'),
    ProductCategoryModel(productId: '247', categoryId: '25'),
    ProductCategoryModel(productId: '248', categoryId: '7'),
    ProductCategoryModel(productId: '248', categoryId: '25'),
    ProductCategoryModel(productId: '249', categoryId: '7'),
    ProductCategoryModel(productId: '249', categoryId: '25'),
    ProductCategoryModel(productId: '250', categoryId: '7'),
    ProductCategoryModel(productId: '250', categoryId: '25'),
    ProductCategoryModel(productId: '251', categoryId: '7'),
    ProductCategoryModel(productId: '251', categoryId: '25'),
    ProductCategoryModel(productId: '252', categoryId: '7'),
    ProductCategoryModel(productId: '252', categoryId: '25'),
    ProductCategoryModel(productId: '253', categoryId: '7'),
    ProductCategoryModel(productId: '253', categoryId: '25'),
    ProductCategoryModel(productId: '254', categoryId: '7'),
    ProductCategoryModel(productId: '254', categoryId: '25'),
    ProductCategoryModel(productId: '255', categoryId: '7'),
    ProductCategoryModel(productId: '255', categoryId: '25'),
    ProductCategoryModel(productId: '256', categoryId: '7'),
    ProductCategoryModel(productId: '256', categoryId: '25'),
    ProductCategoryModel(productId: '257', categoryId: '7'),
    ProductCategoryModel(productId: '257', categoryId: '25'),

    ProductCategoryModel(productId: '259', categoryId: '7'),
    ProductCategoryModel(productId: '259', categoryId: '26'),
    ProductCategoryModel(productId: '260', categoryId: '7'),
    ProductCategoryModel(productId: '260', categoryId: '26'),
    ProductCategoryModel(productId: '261', categoryId: '7'),
    ProductCategoryModel(productId: '261', categoryId: '26'),
    ProductCategoryModel(productId: '262', categoryId: '7'),
    ProductCategoryModel(productId: '262', categoryId: '26'),
    ProductCategoryModel(productId: '263', categoryId: '7'),
    ProductCategoryModel(productId: '263', categoryId: '26'),
    ProductCategoryModel(productId: '264', categoryId: '7'),
    ProductCategoryModel(productId: '264', categoryId: '26'),
    ProductCategoryModel(productId: '265', categoryId: '7'),
    ProductCategoryModel(productId: '265', categoryId: '26'),
    ProductCategoryModel(productId: '266', categoryId: '7'),
    ProductCategoryModel(productId: '266', categoryId: '26'),
    ProductCategoryModel(productId: '267', categoryId: '7'),
    ProductCategoryModel(productId: '267', categoryId: '26'),
    ProductCategoryModel(productId: '268', categoryId: '7'),
    ProductCategoryModel(productId: '268', categoryId: '26'),
    ProductCategoryModel(productId: '269', categoryId: '7'),
    ProductCategoryModel(productId: '269', categoryId: '26'),
    ProductCategoryModel(productId: '270', categoryId: '7'),
    ProductCategoryModel(productId: '270', categoryId: '26'),
    ProductCategoryModel(productId: '271', categoryId: '7'),
    ProductCategoryModel(productId: '271', categoryId: '26'),
    ProductCategoryModel(productId: '272', categoryId: '7'),
    ProductCategoryModel(productId: '272', categoryId: '26'),
    ProductCategoryModel(productId: '273', categoryId: '7'),
    ProductCategoryModel(productId: '273', categoryId: '26'),
    ProductCategoryModel(productId: '274', categoryId: '7'),
    ProductCategoryModel(productId: '274', categoryId: '26'),
    ProductCategoryModel(productId: '275', categoryId: '7'),
    ProductCategoryModel(productId: '275', categoryId: '26'),
    ProductCategoryModel(productId: '276', categoryId: '7'),
    ProductCategoryModel(productId: '276', categoryId: '27'),
    ProductCategoryModel(productId: '277', categoryId: '7'),
    ProductCategoryModel(productId: '277', categoryId: '27'),
    ProductCategoryModel(productId: '278', categoryId: '7'),
    ProductCategoryModel(productId: '278', categoryId: '26'),
    //040 after product 005

  ];

  /// -- List of all Products
  static final List<ProductModel> products = [
    ProductModel(
      id: '001',
      title: 'Apple iPhone 13 128GB Blue',
      stock: 15,
      price: 633,
      isFeatured: true,
      thumbnail: TImages.productImage116,
      description: 'Apple iPhone 13 128GB Blue, green, red, purple & white, 15.4 cm (6.1 inch) Super Retina XDR display Cinema mode automatically adds shallow depth of field and shifts the focus in your videos12 MP TrueDepth front camera with night mode, 4K HDR recording with Dolby VisionA15 Bionic chip for super-fast performanceUp to 19 hours of video playback5G for super-fast downloads and streaming in the highest qualityiOS 15 is packed with new features so you can do more with your iPhone than ever before Supports MagSafe accessories for easy docking and faster wireless charging',
      brand: BrandModel(id: '3', image: TImages.appleLogo, name: 'Apple', productsCount: 265, isFeatured: true),
      images: [TImages.productImage115, TImages.productImage116, TImages.productImage117, TImages.productImage119, TImages.productImage120,],
      salePrice: 30,
      sku: 'ABR4568',
      categoryId: '8',
      productAttributes: [
        ProductAttributeModel(name: 'Color', values: ['Green', 'Black', 'Red','blue','purple','white']),
        ProductAttributeModel(name: 'Memory Size', values: ['128GB', '256GB', '512GB']),
      ],
      productVariations: [
        ProductVariationModel(
            id: '1',
            stock: 34,
            price: 134,
            salePrice: 122.6,
            image: TImages.productImage115,
            description: 'This is a Product description for Green Nike sports shoe.',
            attributeValues: {'Color': 'Green', 'Memory Size': '128GB'}),

        ProductVariationModel(
            id: '2', stock: 15, price: 132, image: TImages.productImage116, attributeValues: {'Color': 'Blue', 'Size': '128GB'}),
        ProductVariationModel(
            id: '3', stock: 0, price: 234, image: TImages.productImage117, attributeValues: {'Color': 'Green', 'Size': '128GB'}),
        ProductVariationModel(
            id: '4', stock: 222, price: 232, image: TImages.productImage118, attributeValues: {'Color': 'Red', 'Size': '128GB'}),
        ProductVariationModel(
            id: '5', stock: 0, price: 334, image: TImages.productImage119, attributeValues: {'Color': 'Purple', 'Size': '128GB'}),
        ProductVariationModel(
            id: '6', stock: 11, price: 332, image: TImages.productImage120, attributeValues: {'Color': 'white', 'Size': '128GB'}),
      ],
      productType: ProductType.variable.toString(),
    ),
    ProductModel(
      id: '002',
      title: 'Samsung Galaxy A55 5G 128GB (A556B) Awesome Iceblue',
      stock: 15,
      price: 35,
      isFeatured: true,
      thumbnail: TImages.productImage3,
      description:
      'The Samsung Galaxy A55 offers impressive features for different moments in your life. With AI-assisted portrait shots at night and action-packed 4K videos, you can capture wow moments. The powerful processor and large Super AMOLED display ensure high-speed experiences.The high level of data security and IP67 certification make the smartphone ideal for private moments. And with 8 GB RAM and up to 256 GB internal storage, you have enough space for productive moments and easy sharing in the Galaxy Ecosystem. It sounds like a versatile and powerful device',
      brand: BrandModel(id: '1', image: TImages.samsungLogo, name: 'Samsung'),
      images: [TImages.productImage1, TImages.productImage2, TImages.productImage3, TImages.productImage4],
      salePrice: 30,
      sku: 'ABR4568',
      categoryId: '9',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['128GB', '256GB']),
        ProductAttributeModel(name: 'Color', values: ['Black','Purple','yellow', 'Blue']),
      ],
  productVariations: [
  ProductVariationModel(
  id: '1',
  stock: 34,
  price: 134,
  salePrice: 122.6,
  image: TImages.productImage1,
  description: 'This is a Product description for Green Nike sports shoe.',
  attributeValues: {'Color': 'Purple', 'Memory Size': '128GB'}),

  ProductVariationModel(
  id: '2', stock: 15, price: 132, image: TImages.productImage2, attributeValues: {'Color': 'Black', 'Size': '128GB'}),
  ProductVariationModel(
  id: '3', stock: 0, price: 234, image: TImages.productImage3, attributeValues: {'Color': 'Yellow', 'Size': '128GB'}),
  ProductVariationModel(
  id: '4', stock: 222, price: 232, image: TImages.productImage4, attributeValues: {'Color': 'Red', 'Size': '128GB'}),
  ],
  productType: ProductType.variable.toString(),
  ),
    ProductModel(
      id: '003',
      title: 'Leather brown Jacket',
      stock: 15,
      price: 38000,
      isFeatured: false,
      thumbnail: TImages.productImage64,
      description:
      'This is a Product description for Leather brown Jacket. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '6', image: TImages.zaraLogo, name: 'ZARA'),
      images: [TImages.productImage64, TImages.productImage65, TImages.productImage66, TImages.productImage67],
      salePrice: 30,
      sku: 'ABR4568',
      categoryId: '16',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),
    ProductModel(
      id: '004',
      title: '4 Color collar t-shirt dry fit',
      stock: 15,
      price: 135,
      isFeatured: false,
      thumbnail: TImages.productImage60,
      description:
      'This is a Product description for 4 Color collar t-shirt dry fit. There are more things that can be added but its just a demo and nothing else.',
      brand: BrandModel(id: '6', image: TImages.zaraLogo, name: 'ZARA'),
      images: [TImages.productImage60, TImages.productImage61, TImages.productImage62, TImages.productImage63],
      salePrice: 30,
      sku: 'ABR4568',
      categoryId: '16',
      productAttributes: [
        ProductAttributeModel(name: 'Color', values: ['Red', 'Yellow', 'Green', 'Blue']),
        ProductAttributeModel(name: 'Size', values: ['EU 30', 'EU 32', 'EU 34']),
      ],
      productVariations: [
        ProductVariationModel(
            id: '1',
            stock: 34,
            price: 134,
            salePrice: 122.6,
            image: TImages.productImage60,
            description: 'This is a Product description for 4 Color collar t-shirt dry fit',
            attributeValues: {'Color': 'Red', 'Size': 'EU 34'}),
        ProductVariationModel(
            id: '2', stock: 15, price: 132, image: TImages.productImage60, attributeValues: {'Color': 'Red', 'Size': 'EU 32'}),
        ProductVariationModel(
            id: '3', stock: 0, price: 234, image: TImages.productImage61, attributeValues: {'Color': 'Yellow', 'Size': 'EU 34'}),
        ProductVariationModel(
            id: '4', stock: 222, price: 232, image: TImages.productImage61, attributeValues: {'Color': 'Yellow', 'Size': 'EU 32'}),
        ProductVariationModel(
            id: '5', stock: 0, price: 334, image: TImages.productImage62, attributeValues: {'Color': 'Green', 'Size': 'EU 34'}),
        ProductVariationModel(
            id: '6', stock: 11, price: 332, image: TImages.productImage62, attributeValues: {'Color': 'Green', 'Size': 'EU 30'}),
        ProductVariationModel(
            id: '7', stock: 0, price: 334, image: TImages.productImage63, attributeValues: {'Color': 'Blue', 'Size': 'EU 30'}),
        ProductVariationModel(
            id: '8', stock: 11, price: 332, image: TImages.productImage63, attributeValues: {'Color': 'Blue', 'Size': 'EU 34'}),
      ],
      productType: ProductType.variable.toString(),
    ),

    ///Products after banner
    ProductModel(
      id: '005',
      title: 'Nike Air Jordon Shoes',
      stock: 15,
      price: 35,
      isFeatured: false,
      thumbnail: TImages.productImage10,
      description: 'Nike Air Jordon Shoes for running. Quality product, Long Lasting',
      brand: BrandModel(id: '1', image: TImages.nikeLogo, name: 'Nike', productsCount: 265, isFeatured: true),
      images: [TImages.productImage7, TImages.productImage8, TImages.productImage9, TImages.productImage10],
      salePrice: 30,
      sku: 'ABR4568',
      categoryId: '8',
      productAttributes: [
        ProductAttributeModel(name: 'Color', values: ['Orange', 'Black', 'Brown']),
        ProductAttributeModel(name: 'Size', values: ['EU 30', 'EU 32', 'EU 34']),
      ],
      productVariations: [
        ProductVariationModel(
            id: '1',
            stock: 16,
            price: 36,
            salePrice: 12.6,
            image: TImages.productImage8,
            description:
            'Flutter is Google’s mobile UI open source framework to build high-quality native (super fast) interfaces for iOS and Android apps with the unified codebase.',
            attributeValues: {'Color': 'Orange', 'Size': 'EU 34'}),
        ProductVariationModel(
            id: '2', stock: 15, price: 35, image: TImages.productImage7, attributeValues: {'Color': 'Black', 'Size': 'EU 32'}),
        ProductVariationModel(
            id: '3', stock: 14, price: 34, image: TImages.productImage9, attributeValues: {'Color': 'Brown', 'Size': 'EU 34'}),
        ProductVariationModel(
            id: '4', stock: 13, price: 33, image: TImages.productImage7, attributeValues: {'Color': 'Black', 'Size': 'EU 34'}),
        ProductVariationModel(
            id: '5', stock: 12, price: 32, image: TImages.productImage9, attributeValues: {'Color': 'Brown', 'Size': 'EU 32'}),
        ProductVariationModel(
            id: '6', stock: 11, price: 31, image: TImages.productImage8, attributeValues: {'Color': 'Orange', 'Size': 'EU 32'}),
      ],
      productType: ProductType.variable.toString(),
    ),
    ProductModel(
      id: '006',
      title: 'SAMSUNG Galaxy S9 (Pink, 64 GB)  (4 GB RAM)',
      stock: 15,
      price: 750,
      isFeatured: false,
      thumbnail: TImages.productImage11,
      description: 'SAMSUNG Galaxy S9 (Pink, 64 GB)  (4 GB RAM), Long Battery timing',
      brand: BrandModel(id: '7', image: TImages.appleLogo, name: 'Samsung'),
      images: [TImages.productImage11, TImages.productImage12, TImages.productImage13, TImages.productImage12],
      salePrice: 650,
      sku: 'ABR4568',
      categoryId: '2',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),
    ProductModel(
      id: '007',
      title: 'TOMI Dog food',
      stock: 15,
      price: 20,
      isFeatured: false,
      thumbnail: TImages.productImage18,
      description:
      'This is a Product description for TOMI Dog food. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '7', image: TImages.appleLogo, name: 'Tomi'),
      salePrice: 10,
      sku: 'ABR4568',
      categoryId: '4',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),
    //008 after 040
    ProductModel(
      id: '009',
      title: 'Nike Air Jordon 19 Blue',
      stock: 15,
      price: 400,
      isFeatured: false,
      thumbnail: TImages.productImage19,
      description:
      'This is a Product description for Nike Air Jordon. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '1', image: TImages.nikeLogo, name: 'Nike'),
      images: [TImages.productImage19, TImages.productImage20, TImages.productImage21, TImages.productImage22],
      salePrice: 200,
      sku: 'ABR4568',
      categoryId: '8',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),
    ProductModel(
      id: '010',
      title: 'Nike Air Jordon 6 Orange',
      stock: 15,
      price: 400,
      thumbnail: TImages.productImage20,
      description:
      'This is a Product description for Nike Air Jordon. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '1', image: TImages.nikeLogo, name: 'Nike'),
      images: [TImages.productImage20, TImages.productImage23, TImages.productImage21, TImages.productImage22],
      // salePrice: 200,
      sku: 'ABR4568',
      categoryId: '8',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),
    ProductModel(
      id: '011',
      title: 'Nike Air Max Red & Black',
      stock: 15,
      price: 600,
      isFeatured: true,
      thumbnail: TImages.productImage21,
      description:
      'This is a Product description for Nike Air Max. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '1', image: TImages.nikeLogo, name: 'Nike'),
      images: [TImages.productImage21, TImages.productImage20, TImages.productImage19, TImages.productImage22],
      salePrice: 400,
      sku: 'ABR4568',
      categoryId: '8',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),
    ProductModel(
      id: '012',
      title: 'Nike Basketball shoes Black & Green',
      stock: 15,
      price: 600,
      isFeatured: false,
      thumbnail: TImages.productImage22,
      description:
      'This is a Product description for Nike Basketball shoes. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '1', image: TImages.nikeLogo, name: 'Nike'),
      images: [TImages.productImage22, TImages.productImage20, TImages.productImage21, TImages.productImage23],
      salePrice: 400,
      sku: 'ABR4568',
      categoryId: '8',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),
    ProductModel(
      id: '013',
      title: 'Nike wild horse shoes',
      stock: 15,
      price: 600,
      isFeatured: false,
      thumbnail: TImages.productImage23,
      description:
      'This is a Product description for Nike wild horse shoes. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '1', image: TImages.nikeLogo, name: 'Nike'),
      images: [TImages.productImage23, TImages.productImage20, TImages.productImage21, TImages.productImage22],
      salePrice: 400,
      sku: 'ABR4568',
      categoryId: '8',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),
    //Track suits
    ProductModel(
      id: '014',
      title: 'Nike Track suit red',
      stock: 15,
      price: 500,
      isFeatured: true,
      thumbnail: TImages.productImage26,
      description:
      'This is a Product description for Nike Track suit red. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '1', image: TImages.nikeLogo, name: 'Nike'),
      images: [TImages.productImage26, TImages.productImage24, TImages.productImage25, TImages.productImage27],
      // salePrice: 400,
      sku: 'ABR4568',
      categoryId: '9',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),
    ProductModel(
      id: '015',
      title: 'Nike Track suit Black',
      stock: 15,
      price: 200,
      thumbnail: TImages.productImage24,
      description:
      'This is a Product description for Nike Track suit Black. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '1', image: TImages.nikeLogo, name: 'Nike'),
      images: [TImages.productImage24, TImages.productImage26, TImages.productImage25, TImages.productImage27],
      // salePrice: 400,
      sku: 'ABR4568',
      categoryId: '9',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),
    ProductModel(
      id: '016',
      title: 'Nike Track suit Blue',
      stock: 15,
      price: 100,
      thumbnail: TImages.productImage25,
      description:
      'This is a Product description for Nike Track suit Blue. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '1', image: TImages.nikeLogo, name: 'Nike'),
      images: [TImages.productImage25, TImages.productImage24, TImages.productImage26, TImages.productImage27],
      // salePrice: 400,
      sku: 'ABR4568',
      categoryId: '9',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),
    ProductModel(
      id: '017',
      title: 'Nike Track suit Parrot Green',
      stock: 15,
      price: 350,
      thumbnail: TImages.productImage27,
      description:
      'This is a Product description for Nike Track suit Parrot Green. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '1', image: TImages.nikeLogo, name: 'Nike'),
      images: [TImages.productImage27, TImages.productImage24, TImages.productImage25, TImages.productImage26],
      // salePrice: 400,
      sku: 'ABR4568',
      categoryId: '9',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),
    //Sports Equipments
    ProductModel(
      id: '018',
      title: 'Adidas Football',
      stock: 15,
      price: 40,
      isFeatured: true,
      thumbnail: TImages.productImage28,
      description:
      'This is a Product description for Football. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '2', image: TImages.adidasLogo, name: 'Adidas'),
      images: [TImages.productImage28, TImages.productImage29, TImages.productImage30, TImages.productImage31],
      // salePrice: 400,
      sku: 'ABR4568',
      categoryId: '10',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),
    ProductModel(
      id: '019',
      title: 'Baseball Bat',
      stock: 15,
      price: 30,
      thumbnail: TImages.productImage29,
      description:
      'This is a Product description for Baseball Bat. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '2', image: TImages.adidasLogo, name: 'Adidas'),
      images: [TImages.productImage29, TImages.productImage28, TImages.productImage30, TImages.productImage31],
      // salePrice: 400,
      sku: 'ABR4568',
      categoryId: '10',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),
    ProductModel(
      id: '020',
      title: 'Cricket Bat',
      stock: 15,
      price: 25,
      thumbnail: TImages.productImage30,
      description:
      'This is a Product description for Cricket Bat. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '2', image: TImages.adidasLogo, name: 'Adidas'),
      images: [TImages.productImage30, TImages.productImage29, TImages.productImage28, TImages.productImage31],
      // salePrice: 400,
      sku: 'ABR4568',
      categoryId: '10',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),
    ProductModel(
      id: '021',
      title: 'Tennis Racket',
      stock: 15,
      price: 54,
      thumbnail: TImages.productImage31,
      description:
      'This is a Product description for Tennis Racket. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '2', image: TImages.adidasLogo, name: 'Adidas'),
      images: [TImages.productImage31, TImages.productImage29, TImages.productImage30, TImages.productImage28],
      // salePrice: 400,1
      sku: 'ABR4568',
      categoryId: '10',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),

    ///Furniture
    //bedroom
    ProductModel(
      id: '022',
      title: 'Pure Wooden Bed',
      stock: 15,
      price: 950,
      isFeatured: true,
      thumbnail: TImages.productImage32,
      description:
      'Flutter is Google’s mobile UI open source framework to build high-quality native (super fast) interfaces for iOS and Android apps with the unified codebase.',
      brand: BrandModel(id: '8', image: TImages.kenwoodLogo, name: 'Kenwood'),
      images: [TImages.productImage43, TImages.productImage44, TImages.productImage45, TImages.productImage46],
      salePrice: 600,
      sku: 'ABR4568',
      categoryId: '11',
      productAttributes: [
        ProductAttributeModel(name: 'Color', values: ['Black', 'Grey', 'Brown']),
        ProductAttributeModel(name: 'Size', values: ['EU 30', 'EU 32', 'EU 34']),
      ],
      productVariations: [
        ProductVariationModel(
            id: '1',
            stock: 16,
            price: 36,
            salePrice: 12.6,
            image: TImages.productImage32,
            description:
            'Flutter is Google’s mobile UI open source framework to build high-quality native (super fast) interfaces for iOS and Android apps with the unified codebase.',
            attributeValues: {'Color': 'Brown', 'Size': 'EU 34'}),
        ProductVariationModel(
            id: '2', stock: 15, price: 35, image: TImages.productImage45, attributeValues: {'Color': 'Brown', 'Size': 'EU 32'}),
        ProductVariationModel(
            id: '3', stock: 14, price: 34, image: TImages.productImage46, attributeValues: {'Color': 'Brown', 'Size': 'EU 30'}),
        ProductVariationModel(
            id: '4', stock: 13, price: 33, image: TImages.productImage43, attributeValues: {'Color': 'Black', 'Size': 'EU 32'}),
        ProductVariationModel(
            id: '5', stock: 12, price: 32, image: TImages.productImage43, attributeValues: {'Color': 'Black', 'Size': 'EU 34'}),
        ProductVariationModel(
            id: '6', stock: 11, price: 31, image: TImages.productImage44, attributeValues: {'Color': 'Grey', 'Size': 'EU 32'}),
      ],
      productType: ProductType.variable.toString(),
    ),
    ProductModel(
      id: '023',
      title: 'Side Table Lamp',
      stock: 15,
      price: 25,
      thumbnail: TImages.productImage33,
      description:
      'This is a Product description for Side Table Lamp. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '8', image: TImages.kenwoodLogo, name: 'Kenwood'),
      // salePrice: 400,1
      sku: 'ABR4568',
      categoryId: '11',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),
    ProductModel(
      id: '024',
      title: 'Bedroom Sofa',
      stock: 15,
      price: 25,
      thumbnail: TImages.productImage34,
      description:
      'This is a Product description for Bedroom Sofa. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '8', image: TImages.kenwoodLogo, name: 'Kenwood'),
      // salePrice: 400,1
      sku: 'ABR4568',
      categoryId: '11',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),
    ProductModel(
      id: '025',
      title: 'Wardrobe for Bedroom',
      stock: 15,
      price: 56,
      thumbnail: TImages.productImage35,
      description:
      'This is a Product description for Bedroom Wardrobe. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '8', image: TImages.kenwoodLogo, name: 'Kenwood'),
      // salePrice: 400,1
      sku: 'ABR4568',
      categoryId: '11',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),
    //Kitchen
    ProductModel(
      id: '026',
      title: 'Kitchen Counter',
      stock: 15,
      price: 1012,
      thumbnail: TImages.productImage36,
      description:
      'This is a Product description for Kitchen Counter. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '2', image: TImages.adidasLogo, name: 'Adidas'),
      // salePrice: 400,1
      sku: 'ABR4568',
      categoryId: '12',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),
    ProductModel(
      id: '027',
      title: 'Dinning Table',
      stock: 15,
      price: 1012,
      thumbnail: TImages.productImage37,
      description:
      'This is a Product description for Dinning Table. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '2', image: TImages.adidasLogo, name: 'Adidas'),
      // salePrice: 400,1
      sku: 'ABR4568',
      categoryId: '12',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),
    ProductModel(
      id: '028',
      title: 'Refrigerator',
      stock: 15,
      price: 987,
      thumbnail: TImages.productImage38,
      description:
      'This is a Product description for Refrigerator. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '2', image: TImages.adidasLogo, name: 'Adidas'),
      // salePrice: 400,1
      sku: 'ABR4568',
      categoryId: '12',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),
    //Office
    ProductModel(
      id: '029',
      title: 'Office Chair Red',
      stock: 15,
      price: 150,
      thumbnail: TImages.productImage39,
      description:
      'This is a Product description for Office Chair. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '9', image: TImages.ikeaLogo, name: 'IKEA'),
      // salePrice: 400,1
      sku: 'ABR4568',
      categoryId: '13',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),
    ProductModel(
      id: '030',
      title: 'Office Chair White',
      stock: 15,
      price: 140,
      thumbnail: TImages.productImage40,
      description:
      'This is a Product description for Office Chair. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '9', image: TImages.ikeaLogo, name: 'IKEA'),
      // salePrice: 400,1
      sku: 'ABR4568',
      categoryId: '13',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),
    ProductModel(
      id: '031',
      title: 'Office Desk Red',
      stock: 15,
      price: 360,
      thumbnail: TImages.productImage41,
      description:
      'This is a Product description for Office Desk. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '9', image: TImages.ikeaLogo, name: 'IKEA'),
      // salePrice: 400,1
      sku: 'ABR4568',
      categoryId: '13',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),
    ProductModel(
      id: '032',
      title: 'Office Desk brown',
      stock: 15,
      price: 400,
      thumbnail: TImages.productImage42,
      description:
      'This is a Product description for Office Desk. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '9', image: TImages.ikeaLogo, name: 'IKEA'),
      // salePrice: 400,1
      sku: 'ABR4568',
      categoryId: '13',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),

    ///Electronics
    //Laptops
    ProductModel(
      id: '033',
      title: 'Acer Laptop RAM 8gb to 16gb 512gb to 2tb',
      stock: 15,
      price: 950,
      isFeatured: true,
      thumbnail: TImages.productImage56,
      description:
      'This is a Product description for Acer Laptop. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '10', image: TImages.acerLogo, name: 'Acer'),
      images: [TImages.productImage56, TImages.productImage47, TImages.productImage57, TImages.productImage58],
      salePrice: 800,
      sku: 'ABR4568',
      categoryId: '14',
      productAttributes: [
        ProductAttributeModel(name: 'Ram', values: ['6', '8', '16']),
        ProductAttributeModel(name: 'SSD', values: ['512', '1 tb', '2 tb']),
      ],
      productVariations: [
        ProductVariationModel(
            id: '1',
            stock: 16,
            price: 400,
            salePrice: 350,
            image: TImages.productImage56,
            description:
            'This is a Product description for Acer Laptop. There are more things that can be added but i am just practicing and nothing else.',
            attributeValues: {'Ram': '6', 'hard': '512'}),
        ProductVariationModel(id: '2', stock: 15, price: 450, image: TImages.productImage47, attributeValues: {'Ram': '8', 'hard': '512'}),
        ProductVariationModel(id: '3', stock: 14, price: 470, image: TImages.productImage59, attributeValues: {'Ram': '8', 'hard': '1 tb'}),
        ProductVariationModel(id: '4', stock: 13, price: 500, image: TImages.productImage58, attributeValues: {'Ram': '16', 'hard': '512'}),
        ProductVariationModel(
            id: '5', stock: 12, price: 650, image: TImages.productImage57, attributeValues: {'Ram': '16', 'hard': '1 tb'}),
        ProductVariationModel(
            id: '6', stock: 11, price: 800, image: TImages.productImage59, attributeValues: {'Ram': '16', 'hard': '2 tb'}),
      ],
      productType: ProductType.variable.toString(),
    ),
    ProductModel(
      id: '034',
      title: 'Acer Laptop 6gb 1tb',
      stock: 15,
      price: 400,
      thumbnail: TImages.productImage48,
      description:
      'This is a Product description for Acer Laptop. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '10', image: TImages.acerLogo, name: 'Acer'),
      // salePrice: 400,1
      sku: 'ABR4568',
      categoryId: '14',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),
    ProductModel(
      id: '035',
      title: 'Acer Laptop 6gb 500Gb',
      stock: 15,
      price: 400,
      thumbnail: TImages.productImage49,
      description:
      'This is a Product description for Acer Laptop. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '10', image: TImages.acerLogo, name: 'Acer'),
      // salePrice: 400,1
      sku: 'ABR4568',
      categoryId: '14',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),
    ProductModel(
      id: '036',
      title: 'Acer Laptop 4gb 500Gb',
      stock: 15,
      price: 400,
      thumbnail: TImages.productImage50,
      description:
      'This is a Product description for Acer Laptop. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '10', image: TImages.acerLogo, name: 'Acer'),
      // salePrice: 400,1
      sku: 'ABR4568',
      categoryId: '14',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),
    //Mobiles
    ProductModel(
      id: '037',
      title: 'Iphone 13 pro 512gb',
      stock: 15,
      price: 999,
      thumbnail: TImages.productImage51,
      description:
      'This is a Product description for Iphone. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '5', image: TImages.appleLogo, name: 'Apple'),
      // salePrice: 400,1
      sku: 'ABR4568',
      categoryId: '15',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),
    ProductModel(
      id: '038',
      title: 'Iphone 14 pro 512gb',
      stock: 15,
      price: 999,
      thumbnail: TImages.productImage52,
      description:
      'This is a Product description for Iphone. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '5', image: TImages.appleLogo, name: 'Apple'),
      // salePrice: 400,1
      sku: 'ABR4568',
      categoryId: '15',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),
    ProductModel(
      id: '039',
      title: 'Iphone 14 white 512gb',
      stock: 15,
      price: 999,
      thumbnail: TImages.productImage53,
      description:
      'This is a Product description for Iphone. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '5', image: TImages.appleLogo, name: 'Apple'),
      // salePrice: 400,1
      sku: 'ABR4568',
      categoryId: '15',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),
    ProductModel(
      id: '040',
      title: 'Iphone 12, 4 Colors 128gb and 256gb',
      stock: 15,
      price: 950,
      isFeatured: true,
      thumbnail: TImages.productImage70,
      description:
      'This is a Product description for Iphone 12. There are more things that can be added but i am just practicing and nothing else.',
      brand: BrandModel(id: '5', image: TImages.appleLogo, name: 'Apple'),
      images: [TImages.productImage70, TImages.productImage71, TImages.productImage72, TImages.productImage73],
      salePrice: 800,
      sku: 'ABR4568',
      categoryId: '15',
      productAttributes: [
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue', 'Black']),
        ProductAttributeModel(name: 'Storage', values: ['128 gb', '256 gb']),
      ],
      productVariations: [
        ProductVariationModel(
            id: '1',
            stock: 16,
            price: 400,
            salePrice: 350,
            image: TImages.productImage70,
            description:
            'This is a Product description for Iphone 12. There are more things that can be added but i am just practicing and nothing else.',
            attributeValues: {'Color': 'Red', 'Storage': '128 gb'}),
        ProductVariationModel(
            id: '2', stock: 15, price: 450, image: TImages.productImage70, attributeValues: {'Color': 'Red', 'Storage': '256 gb'}),
        ProductVariationModel(
            id: '3', stock: 14, price: 470, image: TImages.productImage71, attributeValues: {'Color': 'Blue', 'Storage': '128 gb'}),
        ProductVariationModel(
            id: '4', stock: 13, price: 500, image: TImages.productImage71, attributeValues: {'Color': 'Blue', 'Storage': '256 gb'}),
        ProductVariationModel(
            id: '5', stock: 12, price: 650, image: TImages.productImage72, attributeValues: {'Color': 'Green', 'Storage': '128 gb'}),
        ProductVariationModel(
            id: '5', stock: 12, price: 650, image: TImages.productImage72, attributeValues: {'Color': 'Green', 'Storage': '256 gb'}),
        ProductVariationModel(
            id: '6', stock: 11, price: 800, image: TImages.productImage73, attributeValues: {'Color': 'Black', 'Storage': '128 gb'}),
        ProductVariationModel(
            id: '6', stock: 11, price: 800, image: TImages.productImage73, attributeValues: {'Color': 'Black', 'Storage': '256 gb'}),
      ],
      productType: ProductType.variable.toString(),
    ),
    ProductModel(
      id: '008',
      title: 'APPLE iPhone 8 (Black, 64 GB)',
      stock: 15,
      price: 480,
      isFeatured: true,
      thumbnail: TImages.productImage14,
      description:
      'Discover comfort and convenience with our reliable keke, built for smooth rides and excellent fuel efficeincy',
      brand: BrandModel(id: '5', image: TImages.appleLogo, name: 'iphone 8'),
      images: [TImages.productImage15, TImages.productImage16, TImages.productImage17, TImages.productImage14],
      salePrice: 380,
      sku: 'ABR4568',
      categoryId: '4',
      productAttributes: [
        ProductAttributeModel(name: 'Size', values: ['EU34', 'EU32']),
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
      ],
      productType: ProductType.single.toString(),
    ),
  ];

  /// -- Sorting Filters for search
  static final sortingFilters = [
    SortFilterModel(id: '1', name: 'Name'),
    SortFilterModel(id: '2', name: 'Lowest Price'),
    SortFilterModel(id: '3', name: 'Most Popular'),
    SortFilterModel(id: '4', name: 'Highest Price'),
    SortFilterModel(id: '5', name: 'Newest'),
    SortFilterModel(id: '6', name: 'Most Suitable'),
  ];

  /// -- Product Reviews
  static final List<ProductReviewModel> productReviews = [
    ProductReviewModel(
      id: '01',
      userId: '001',
      userName: 'John Doe',
      rating: 4.5,
      timestamp: DateTime.now(),
      companyTimestamp: DateTime.now(),
      userImageUrl: TImages.userProfileImage2,
      comment: 'The user interface of the app is quite intuitive. I was able to navigate and make purchases seamlessly. Great job!',
      companyComment:
      'Thank you for your kind words, John! We are delighted to hear about your smooth experience with the app. We always strive to offer an intuitive interface for our users. Stay tuned for more updates!',
    ),
    ProductReviewModel(
      id: '02',
      userId: '002',
      userName: 'Sophia Wilson',
      rating: 3.5,
      timestamp: DateTime.now(),
      companyTimestamp: DateTime.now(),
      userImageUrl: TImages.userProfileImage1,
      comment:
      'I am genuinely impressed with the app design and the variety of products available. The filter and sort features have made shopping so much easier for me!',
      companyComment:
      'Thank you so much, Sophia! We are thrilled to hear you are enjoying the app and finding the features useful. Our goal is to make your shopping experience as efficient and pleasant as possible. Keep exploring, and happy shopping!',
    ),
    ProductReviewModel(
      id: '03',
      userId: '003',
      userName: 'Alex Brown',
      rating: 5,
      timestamp: DateTime.now(),
      companyTimestamp: DateTime.now(),
      userImageUrl: TImages.userProfileImage3,
      comment: 'The app is pretty fast, and the product recommendations are on point! I would love to see more features in the future.',
      companyComment:
      'Thanks for the feedback, Alex! We are thrilled to hear you enjoyed the speed and recommendations. We are constantly working on introducing new features, so keep an eye out for the next update!',
    ),
  ];
}

class SortFilterModel {
  String id;
  String name;

  SortFilterModel({required this.id, required this.name});
}
